title="AMA Sportsman Contest"
playlist={
{"Takeoff","man1",5},
{"Straight Flight (out)","man2",5},
{"Half Reverse Cuban Eight","man3",5},
{"Straight Flight (back)","man4",5},
{"Immelmann turn","man5",5},
{"45 degree Down Line","man6",5},
{"Box exit and Re-Entry","man7",5},
{"One Horizontal Roll","man8",5},
{"Stall Turn without rolls","man9",5},
{"45 degree Up Line","man10",5},
{"Split “S” (half roll, half loop from top)","man11",5},
{"Double Immelmann without Rolls","man12",5},
{"Box exit and Re-Entry","man13",5},
{"Two Inside Loops","man14",5},
{"Half Reverse Cuban Eight","man15",5},
{"Two point (2 of 2) Roll","man16",5},
{"Half Cuban Eight","man17",5},
{"Triangular loop, non-rolling (from bottom)","man18",5},
{"Landing","man19",5},
}