title="AMA Advanced Contest"
playlist={
{"Takeoff"," "," "," ","man83",3},
{"45 degree Upline with 4 point roll"," "," "," ","man84",3},
{"Half square loop from top, half roll down"," "," "," ","man85",3},
{"Slow Roll"," "," "," ","man86",3},
{"Half Cuban with full roll, inverted exit"," "," "," ","man87",3},
{"Triangle loop with one pos snap roll","inverted entry and exit"," "," ","man88",3},
{"Top Hat, 3/4 roll up, 1/4 roll down, inverted entry"," "," "," ","man89",3},
{"Double Immelman 2 of 2 point roll first","full roll second"," "," ","man90",3},
{"Stall turn full roll up"," "," "," ","man91",3},
{"Reverse Cuban Eight with 2 of 4 point rolls"," "," "," ","man92",3},
{"Sharks tooth 1/2 roll on the vertical","2 1/2 rolls reversed on the 45 down line"," "," ","man93",3},
{"Figure Z with 1/2 roll up, inverted exit"," "," "," ","man94",3},
{"Half square loop on corner from top, inverted entry"," "," "," ","man95",3},
{"Figure M with 1/4 rolls"," "," "," ","man96",3},
{"Humpty Bump with Options, 1/2 roll up","or 1/4 roll up and down"," "," ","man97",3},
{"Four point roll"," "," "," ","man98",3},
{"Half square loop with 2 of 4 point roll up"," "," "," ","man99",3},
{"Three turn spin"," "," "," ","man100",3},
{"Landing"," "," "," ","man101",3},
}