title="AMA Advanced Contest"
playlist={
{"Takeoff"," "," "," ","man1",5},
{"45 degree Upline with 4 point roll"," "," "," ","man2",5},
{"Half square loop from top, half roll down"," "," "," ","man3",5},
{"Slow Roll"," "," "," ","man4",5},
{"Half Cuban with full roll, inverted exit"," "," "," ","man5",5},
{"Triangle loop with one pos snap roll","inverted entry and exit"," "," ","man6",5},
{"Top Hat, 3/4 roll up, 1/4 roll down, inverted entry"," "," "," ","man7",5},
{"Double Immelman 2 of 2 point roll first","full roll second"," "," ","man8",5},
{"Stall turn full roll up"," "," "," ","man9",5},
{"Reverse Cuban Eight with 2 of 4 point rolls"," "," "," ","man10",5},
{"Sharks tooth 1/2 roll on the vertical","2 1/2 rolls reversed on the 45 down line"," "," ","man11",5},
{"Figure Z with 1/2 roll up, inverted exit"," "," "," ","man12",5},
{"Half square loop on corner from top, inverted entry"," "," "," ","man13",5},
{"Figure M with 1/4 rolls"," "," "," ","man14",5},
{"Humpty Bump with Options, 1/2 roll up","or 1/4 roll up and down"," "," ","man15",5},
{"Four point roll"," "," "," ","man16",5},
{"Half square loop with 2 of 4 point roll up"," "," "," ","man17",5},
{"Three turn spin"," "," "," ","man18",5},
{"Landing"," "," "," ","man19",5},
}