title="AMA Masters Contest"
playlist={
{"Takeoff"," "," "," ","man102",3},
{"Cuban Eight with full rolls integrated into","the top 90 degrees of both part loops"," "," ","man103",3},
{"Half square loop with 4 of 8 point roll"," "," "," ","man104",3},
{"Square loop from the top with 2 of 4 point rolls"," "," "," ","man105",3},
{"Top Hat from top with options, 1 roll down","2 of 4 point roll up"," "," ","man106",3},
{"2-1/2 turn spin, inverted exit"," "," "," ","man107",3},
{"Humpty bump with roll options, 1/4 or 1/2 rolls","up and down"," "," ","man108",3},
{"Eight Point Roll"," "," "," ","man109",3},
{"Stall Turn, Full roll up, half roll down","inverted exit"," "," ","man110",3},
{"Top Hat 2 of 2 point Roll Up, Snap Roll On Top","2 of 4 point Roll Down"," "," ","man111",3},
{"Half square loop on corner with 1/2 rolls","inverted exit"," "," ","man112",3},
{"Humpty bump from top, 2 of 4 point roll down","full roll up, inverted entry Pull, Push, Push"," "," ","man113",3},
{"Half Square with 1/2 roll"," "," "," ","man114",3},
{"Triangular loop, from bottom, with 2 of 4 point rolls","in 45 degree legs, full roll on top"," "," ","man115",3},
{"Humpty bump with roll options, 1/4 or 1/2 rolls","up and down, inverted exit"," "," ","man116",3},
{"Two 3 of 4 point rolls Reversed, inverted exit"," "," "," ","man117",3},
{"Stall Turn, 4 point roll up, half roll down"," "," "," ","man118",3},
{"Hourglass, Middle entry top first","1 1/2 snap roll down, inverted exit"," "," ","man119",3},
{"Landing"," "," "," ","man120",3},
}