title="AMA Intermediate Contest"
playlist={
{"Takeoff"," "," "," ","man64",3},
{"Double Immelmann with half rolls"," "," "," ","man65",3},
{"Stall Turn without rolls"," "," "," ","man66",3},
{"Reverse Cuban Eight with half rolls"," "," "," ","man67",3},
{"Half Square Loop with full roll up, inverted exit"," "," "," ","man68",3},
{"Two Inside loops from the top, inverted exit"," "," "," ","man69",3},
{"Half loop from the top"," "," "," ","man70",3},
{"Two half rolls reversed, pause in middle"," "," "," ","man71",3},
{"Top Hat with 1/4 rolls up and down"," "," "," ","man72",3},
{"Triangle loop,non rolling base at top"," "," "," ","man73",3},
{"Humpty bump with roll options, half roll up ","or 1/4 roll up and down"," "," ","man74",3},
{"Two horizontal rolls"," "," "," ","man75",3},
{"Sharks Tooth, half roll on 45 degree down line"," "," "," ","man76",3},
{"Square Loop on Corner"," "," "," ","man77",3},
{"Half Reverse Cuban Eight"," "," "," ","man78",3},
{"45 degree upline with 1/2 roll, exit inverted"," "," "," ","man79",3},
{"Half square loop on corner from top, inverted entry"," "," "," ","man80",3},
{"Stall Turn 3/4 roll up, 1/4 roll down"," "," "," ","man81",3},
{"Landing"," "," "," ","man82",3},
}