title="International  P-21"
playlist={
{"Vertical 8 - from Inverted with 1/2 Roll on entry","(ending at center), Push Loop, Pull Loop, 1/2 Roll on Exit","(starting at center) ","- Exit Inverted","man1",9},
{"Stall Turn with Two Consecutive 1/4 Rolls Down"," "," "," ","man2",3},
{"Square Loop on Corner with 1/2 Rolls on 2nd and 4th ","45 Degree Lines"," "," ","man3",4},
{"Figure 9 with Two Consecutive 1/2 Rolls Opposite in the","Up Line - Exit Inverted"," "," ","man4",5},
{"Knife-Edge Flight","with Consecutive 1/4 Roll and 1/2 Roll Opposite,","Consecutive 1/2 Roll, 1/4 Roll Opposite"," ","man5",7},
{"Inverted Split S with Consecutive Two 1/2 Rolls","- Exit Inverted"," "," ","man6",4},
{"Golf Ball with 1/2 Roll Integrated in Top 180 Degrees"," "," "," ","man7",4},
{"Shark Fin with Consective Two 1/4 Rolls on"," 45 Degree Down Line "," "," ","man8",4},
{"Double Immelman with 1/2 Roll Entry, Push 1/2 Loop,","Consecutive Four 1/8 Rolls, Pull 1/2 Loop, 1/2 Roll Exit","- Exit Inverted"," ","man9",9},
{"Push-Push-Push Humpty Bump with 1/2 Roll on Up Line"," (Option: 3/4 Roll Up and 1/4 Roll Down) ","- Exit Inverted"," ","man10",4},
{"Roll Combination with Consecutive 1/2 Roll, Full Roll,","1/2 Roll in Opposite Directions","- Exit Inverted"," ","man11",6},
{"Top Hat with 1/2 Roll in Up Line, Two 1/2 Turn Spin into","a Vertical Downline","(Option: 1/4 Roll Up and 1/4 Roll Down after Spin)"," ","man12",4},
{"Figure Z with Full Roll on 45 Degree Up Line"," "," "," ","man13",3},
{"Comet with Consecutive Two 1/4 Rolls Opposite on 45","Degree Down Line, 1/2 Roll on 45 Degree Up Line"," "," ","man14",11},
{"Roll Combination with Consecutive Four 1/4 Rolls"," "," "," ","man15",3},
{"Half Square Loop on Corner with 1/4 Rolls on","each 45 Degree Up Line ","- Exit Inverted"," ","man16",6},
{"Avalanche - from Inverted pull through a Loop with a","Snap Roll at the Bottom ","- Exit Inverted"," ","man17",5},
}