title="International F-21"
playlist={
{"Golf Ball with 3/4 Roll on 45 Degree Up Line Snap Roll at","Top of 3/4 Loop 3/4 Roll on 45 Down Line"," "," ","man1",3},
{"Half Reverse Cuban 8 with Consecutive Three 1/4 Rolls","with the last 1/4 Roll in Opposite Direction on the 45","Degree Up Line and 3/4 Roll after the 5/8 Loop","- Exit Inverted","man2",3},
{"Horizontal Circle with Two Integrated 1/2 Rolls in ","Opposite Directions","(first 1/2 Roll to the Inside)","- Exit Inverted","man3",3},
{"Top Hat with Consecutive Three 1/4 Rolls in UpLine,","3/4 Snap Roll in Down Line"," "," ","man4",6},
{"Pull-Push-Push Humpty Bump with 1/4 Roll Integrated into","first 1/4 Pull Loop, Full Roll in Up Line, Consecutive Two","1/2 Rolls Opposite in Down Line, 1/4 Roll Integrated into","last 1/4 Loop - Exit Inverted","man5",3},
{"Three Quarter Vertical 8 with 1/2 Roll Integrated into"," Last 45 Degrees of Half Loop and First 45 Degrees of Loop ","- Exit Inverted"," ","man6",3},
{"Stall Turn with Consective 1/4 Roll and 1/2 Roll Opposite","in Up Line and 3/4 Roll inDown Line"," "," ","man7",3},
{"Figure 9 with 1 1/2 Snap Roll in Down Line"," "," "," ","man8",3},
{"Top Hat with 3/4 Roll in Up Line, Full Roll Across Top,","1/4 Roll in Down Line"," "," ","man9",3},
{"Half Square Loop with 1/2 Roll on Entry Prior to Push,","Consecutive 1/2 Roll and Full Roll Opposite in Up Line","- Exit Inverted"," ","man10",3},
{"45 Degree Down Line with 1/4 Roll, Consecutive Two Snap","Rolls Opposite, 1/4 Roll","- Exit Inverted"," ","man11",3},
{"Half 8 Sided Loop with 1/2 Roll on First 45 Degree Up","Line and 1/2 Roll on Second 45 Degree Up Line"," "," ","man12",3},
{"Loop with Two Consecutive Integrated Rolls in Opposite","Directions"," "," ","man13",3},
{"Spin with 2 1/2 Turns"," "," "," ","man14",3},
{"Roll Combination with Consecutive 1/2 Roll, Four 1/4","Rolls in Opposite Direction, 1/2 Roll in Opposite Direction"," "," ","man15",3},
{"Fighter Turn with 3/4 Roll on 45 Degree Up Line and 3/4","Snap Roll on 45 Degree Down Line"," "," ","man16",3},
{"Horizontal Square Circle with 1/4 Roll on Entry","(at Center), 1/2 Roll on 2nd, 3rd and 4th Lines,","1/4 Roll on Exit (at Center)"," ","man17",3},
}