title="AMA Sportsman Contest"
playlist={
{"Takeoff"," "," "," ","man45",3},
{"Straight Flight (out)"," "," "," ","man46",3},
{"Half Reverse Cuban Eight"," "," "," ","man47",3},
{"Straight Flight (back)"," "," "," ","man48",3},
{"Immelmann turn"," "," "," ","man49",3},
{"45 degree Down Line"," "," "," ","man50",3},
{"Box exit and Re-Entry"," "," "," ","man51",3},
{"One Horizontal Roll"," "," "," ","man52",3},
{"Stall Turn without rolls"," "," "," ","man53",3},
{"45 degree Up Line"," "," "," ","man54",3},
{"Split “S” (half roll, half loop from top)"," "," "," ","man55",3},
{"Double Immelmann without Rolls"," "," "," ","man56",3},
{"Box exit and Re-Entry"," "," "," ","man57",3},
{"Two Inside Loops"," "," "," ","man58",3},
{"Half Reverse Cuban Eight"," "," "," ","man59",3},
{"Two point (2 of 2) Roll"," "," "," ","man60",3},
{"Half Cuban Eight"," "," "," ","man61",3},
{"Triangular loop, non-rolling (from bottom)"," "," "," ","man62",3},
{"Landing"," "," "," ","man63",3},
}